### ISSUE TITLE
Android - Crash on Launch

### ISSUE THREAD

**Issue by keithstorm** [Sitata/titanium-google-analytics#41]
Hello, 

I'm using your 3.1.0 release, Titanium SDK. 3.5.1.GA, and Appcelerator Studio with all the latest updates. I'm getting a crash when my Android application launches. I have also imported your sample application and it crashes as well. 

Here is the error message I'm receiving:

```
[ERROR] :  TiApplication: (KrollRuntimeThread) [16,109] Sending event: exception on thread: KrollRuntimeThread msg:java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/analytics.google.test-1/base.apk"],nativeLibraryDirectories=[/data/app/analytics.google.test-1/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libanalytics.google.so"; Titanium 3.5.0,2015/01/12 15:33,0014f83
[ERROR] :  TiApplication: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/analytics.google.test-1/base.apk"],nativeLibraryDirectories=[/data/app/analytics.google.test-1/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libanalytics.google.so"
[ERROR] :  TiApplication: 	at java.lang.Runtime.loadLibrary(Runtime.java:366)
[ERROR] :  TiApplication: 	at java.lang.System.loadLibrary(System.java:988)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:132)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:99)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:185)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)
```

The module works great on iOS, but I'm not having much luck with Android. I've tried a Samsung Note 4 Emulator, Galaxy S3 device, and RAZR HD device. I've looked through all your previous closed issues to no avail. I really appreciate any help you can provide.

**Comment by keithstorm** [comment]
Found the issue. Libs folder was missing from my android folder. Sorry for the inconvenience.

**Comment by astjohn** [comment]
Not at all. Glad you got it sorted out.
