### ISSUE TITLE
Android I can't build in 4.1.0

### ISSUE THREAD

**Issue by ldpalazon** [Sitata/titanium-google-analytics#46]
Hello, 
I use this module in iOS and all is perfect, but, I'm linux, when I try to compile in 4.1.0.GA for android it shows this error:
[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/LocationSource;
[ERROR] :  	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
[ERROR] :  	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
[ERROR] :  	at com.android.dx.command.dexer.Main.processClass(Main.java:732)
[ERROR] :  	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
[ERROR] :  	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
[ERROR] :  	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
[ERROR] :  	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
[ERROR] :  	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
[ERROR] :  	at com.android.dx.command.dexer.Main.run(Main.java:246)
[ERROR] :  	at com.android.dx.command.dexer.Main.main(Main.java:215)
[ERROR] :  	at com.android.dx.command.Main.main(Main.java:106)
[ERROR] :  1 error; aborting
TRACE  | titanium exited with exit code 1
ERROR  | Error: ti run exited with error code 1
    at ChildProcess.<anonymous> (/home/lightdown/.appcelerator/install/4.1.2/package/node_modules/appc-cli-titanium/plugins/run.js:84:66)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:820:12)
[ERROR] Application Installer abnormal process termination. Process exit value was 1

it show the error when I include the module in tiapp.xml
Anybody knows any solution?

Thanks

**Comment by achimhoth** [comment]
I'm having the same problem...

**Comment by achimhoth** [comment]
Even after removing the plugin I am now unable to deploy to an Android device. iOS is running fine though.

**Comment by g0ld2k** [comment]
Did you ever find a solution to this?

**Comment by achimhoth** [comment]
Yes. It has something to do with the Google Play libraries in the modules that you use. Try deleting them in every used module except one.

**Comment by flaviolacer** [comment]
Hi,

You can downgrade the ti.map from 2.3.3 to 2.3.1  in tiapp.xml. Not good but fixed all compatibility issues.

**Comment by ldpalazon** [comment]
Thanks!!!

2015-09-30 0:13 GMT+02:00 flaviolacer <notifications@github.com>:

**Comment by sschueller** [comment]
Same Problem in Ti. SDK 5.0.2. Downgrade works but not sure what might be broken in Ti.map because of the downgrade.

**Comment by efrainpb** [comment]
Hi
I'm having the same problem, but i use specific functions of Ti.map 2.3.6. When run my app return the next log.  Someone has an idea

`[INFO] :   art: art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: obj == null
[INFO] :   art: art/runtime/check_jni.cc:65]     in call to CallVoidMethodV
[INFO] :   art: art/runtime/check_jni.cc:65]     from void org.appcelerator.kroll.runtime.v8.V8Runtime.nativeRunModule(java.lang.String, java.lang.String, org.appcelerator.kroll.KrollProxySupport)
[INFO] :   art: art/runtime/check_jni.cc:65] "KrollRuntimeThread" prio=5 tid=17 Runnable
[INFO] :   art: art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x12c003a0 self=0xab2e0a40
[INFO] :   art: art/runtime/check_jni.cc:65]   | sysTid=7240 nice=0 cgrp=default sched=0/0 handle=0xf4287000
[INFO] :   art: art/runtime/check_jni.cc:65]   | state=R schedstat=( 381384112 27324374 306 ) utm=37 stm=1 core=7 HZ=100
[INFO] :   art: art/runtime/check_jni.cc:65]   | stack=0xe275f000-0xe2761000 stackSize=1052KB
[INFO] :   art: art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
[INFO] :   art: art/runtime/check_jni.cc:65]   native: #00 pc 00004be4  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext*)+23)
[INFO] :   art: art/runtime/check_jni.cc:65]   native: #01 pc 000031b5  /system/lib/libbacktrace_libc++.so (Backtrace::Unwind(unsigned int, ucontext*)+8)
[INFO] :   art: art/runtime/check_jni.cc:65]   native: #02 pc 00242f1f  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*, BacktraceMap*)+70)
[INFO] :   art: art/runtime/check_jni.cc:65]   native: #03 pc 0022767f  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, BacktraceMap*) const+154)
[INFO] :   art: art/runtime/check_jni.cc:65]   native: #04 pc 000b00dd  /system/lib/libart.so (art::JniAbort(char const*, char const*)+584)
[INFO] :   art: art/runtime/check_jni.cc:65]   native: #05 pc 000b0825  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+60)
[INFO] :   art: art/runtime/check_jni.cc:65]   native: #06 pc 0019fe03  /system/lib/libart.so (art::JNI::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+566)
[INFO] :   art: art/runtime/check_jni.cc:65]   native: #07 pc 000810a9  /data/app/com.superchamba.scapp-1/lib/arm/libkroll-v8.so (_JNIEnv::CallVoidMethod(_jobject*, _jmethodID*, ...)+18)
[INFO] :   art: art/runtime/check_jni.cc:65]   native: #08 pc 00081159  /data/app/com.superchamba.scapp-1/lib/arm/libkroll-v8.so (???)
[INFO] :   art: art/runtime/check_jni.cc:65]   native: #09 pc 000817b9  /data/app/com.superchamba.scapp-1/lib/arm/libkroll-v8.so (titanium::Proxy::onPropertyChanged(v8::Local<v8::String>, v8::Local<v8::Value>, v8::AccessorInfo const&)+6)
[INFO] :   art: art/runtime/check_jni.cc:65]   native: #10 pc 002572d4  /data/app/com.superchamba.scapp-1/lib/arm/libkroll-v8.so (???)
[INFO] :   art: art/runtime/check_jni.cc:65]   at org.appcelerator.kroll.runtime.v8.V8Runtime.nativeRunModule(Native method)
[INFO] :   art: art/runtime/check_jni.cc:65]   at org.appcelerator.kroll.runtime.v8.V8Runtime.doRunModule(V8Runtime.java:177)
[INFO] :   art: art/runtime/check_jni.cc:65]   at o
[INFO] :   art: art/runtime/check_jni.cc:65]   at org.appcelerator.kroll.runtime.v8.V8Runtime.handleMessage(V8Runtime.java:203)
[INFO] :   art: art/runtime/check_jni.cc:65]   at android.os.Handler.dispatchMessage(Handler.java:98)
[INFO] :   art: art/runtime/check_jni.cc:65]   at android.os.Looper.loop(Looper.java:211)
[INFO] :   art: art/runtime/check_jni.cc:65]   at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
[INFO] :   art: art/runtime/check_jni.cc:65]
[INFO] :   art: art/runtime/runtime.cc:295] Runtime aborting...
[INFO] :   art: art/runtime/runtime.cc:295] Aborting thread:
[INFO] :   art: art/runtime/runtime.cc:295] "KrollRuntimeThread" prio=5 tid=17 Native
[INFO] :   art: art/runtime/runtime.cc:295]   | group="" sCount=0 dsCount=0 obj=0x12c003a0 self=0xab2e0a40
[INFO] :   art: art/runtime/runtime.cc:295]   | sysTid=7240 nice=0 cgrp=default sched=0/0 handle=0xf4287000
[INFO] :   art: art/runtime/runtime.cc:295]   | state=R schedstat=( 402991305 30388123 403 ) utm=37 stm=4 core=5 HZ=100
[INFO] :   art: art/runtime/runtime.cc:295]   | stack=0xe275f000-0xe2761000 stackSize=1052KB
[INFO] :   art: art/runtime/runtime.cc:295]   | held mutexes= "abort lock" "mutator lock"(shared held)
[INFO] :   art: art/runtime/runtime.cc:295]   native: #00 pc 00004be4  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext*)+23)
[INFO] :   art: art/runtime/runtime.cc:295]   native: #01 pc 000031b5  /system/lib/libbacktrace_libc++.so (Backtrace::Unwind(unsigned int, ucontext*)+8)
[INFO] :   art: art/runtime/runtime.cc:295]   native: #02 pc 00242f1f  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*, BacktraceMap*)+70)
[INFO] :   art: art/runtime/runtime.cc:295]   native: #03 pc 0022767f  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, BacktraceMap*) const+154)
[INFO] :   art: art/runtime/runtime.cc:295]   native: #04 pc 0021762d  /system/lib/libart.so (art::AbortState::DumpThread(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, art::Thread*)+24)
[INFO] :   art: art/runtime/runtime.cc:295]   native: #05 pc 002178dd  /system/lib/libart.so (art::AbortState::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)+436)
[INFO] :   art: art/runtime/runtime.cc:295]   native: #06 pc 00217ab1  /system/lib/libart.so (art::Runtime::Abort()+72)
[INFO] :   art: art/runtime/runtime.cc:295]   native: #07 pc 000a65bb  /system/lib/libart.so (art::LogMessage::~LogMessage()+1322)
[INFO] :   art: art/runtime/runtime.cc:295]   native: #08 pc 000b02cb  /system/lib/libart.so (art::JniAbort(char const*, char const*)+1078)
[INFO] :   art: art/runtime/runtime.cc:295]   native: #09 pc 000b0825  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+60)
[INFO] :   art: art/runtime/runtime.cc:295]   native: #10 pc 0019fe03  /system/lib/libart.so (art::JNI::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+566)
[INFO] :   art: art/runtime/runtime.cc:295]   native: #11 pc 000810a9  /data/app/com.superchamba.scapp-1/lib/arm/libkroll-v8.so (_JNIEnv::CallVoidMethod(_jobject*, _jmethodID*, ...)+18)
[INFO] :   art: art/runtime/runtime.cc:295]   native: #12 pc 00081159  /data/app/com.superchamba.scapp-1/lib/arm/libkroll-v8.so (???)
[INFO] :   art: art/runtime/runtime.cc:295]   native: #13 pc 000817b9  /data/app/com.superchamba.scapp-1/lib/arm/libkroll-v8.so (titanium::Proxy::onPropertyChanged(v8::Local<v8::String>, v8::Local<v8::Value>, v8::AccessorInfo const&)+6)
[INFO] :   art: art/runtime/runtime.cc:295]   native: #14 pc 002572d4  /data/app/com.superchamba.scapp-1/lib/arm/libkroll-v8.so (???)
[INFO] :   art: art/runtime/runtime.cc:295]   at org.appcelerator.kroll.runtime.v8.V8Runtime.nativeRunModule(Native method)
[INFO] :   art: art/runtime/runtime.cc:295]   at org.appcelerator.kroll.runtime.v8.V8Runtime.doRunModule(V8Runtime.java:177)
[INFO] :   art: art/runtime/runtime.cc:295]   at org.appcelerator.kroll.KrollRuntime.handleMessage(KrollRuntime.java:299)
[INFO] :   art: art/runtime/runtime.cc:295]   at org.appcelerator.kroll.runtime.v8.V8Runtime.handleMessage(V8Runtime.java:203)
[INFO] :   art: art/runtime/runtime.cc:295]   at android.os.Handler.dispatchMessage(Handler.java:98)
[INFO] :   art: art/runtime/runtime.cc:295]   at android.os.Looper.loop(Looper.java:211)
[INFO] :   art: art/runtime/runtime.cc:295]   at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
[INFO] :   art: art/runtime/runtime.cc:295] Pending exception java.lang.NoClassDefFoundError thrown by 'unknown throw location'
[INFO] :   art: art/runtime/runtime.cc:295] java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/analytics/GoogleAnalytics;
[INFO] :   art: art/runtime/runtime.cc:295]   at void analytics.google.AnalyticsGoogleModule.<init>() (AnalyticsGoogleModule.java:45)
[INFO] :   art: art/runtime/runtime.cc:295]   at java.lang.Object java.lang.reflect.Constructor.newInstance!(java.lang.Object[], boolean) (Constructor.java:-2)
[INFO] :   art: art/runtime/runtime.cc:295]   at java.lang.Object java.lang.Class.newInstance() (Class.java:1606)
[INFO] :   art: art/runtime/runtime.cc:295]   at org.appcelerator.kroll.KrollProxy org.appcelerator.kroll.KrollProxy.createProxy(java.lang.Class, org.appcelerator.kroll.KrollObject, java.lang.Object[], java.lang.String) (KrollProxy.java:142)
[INFO] :   art: art/runtime/runtime.cc:295]   at void org.appcelerator.kroll.runtime.v8.V8Runtime.nativeRunModule(java.lang.String, java.lang.String, org.appcelerator.kroll.KrollProxySupport) (V8Runtime.java:-2)
[INFO] :   art: art/runtime/runtime.cc:295]   at void org.appcelerator.kroll.runtime.v8.V8Runtime.doRunModule(java.lang.String, java.lang.String, org.appcelerator.kroll.KrollProxySupport) (V8Runtime.java:177)
[INFO] :   art: art/runtime/runtime.cc:295]   at boolean org.appcelerator.kroll.KrollRuntime.handleMessage(android.os.Message) (KrollRuntime.java:299)
[INFO] :   art: art/runtime/runtime.cc:295]   at boolean org.appcelerator.kroll.runtime.v8.V8Runtime.handleMessage(android.os.Message) (V8Runtime.java:203)
[INFO] :   art: art/runtime/runtime.cc:295]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:98)
[INFO] :   art: art/runtime/runtime.cc:295]   at void android.os.Looper.loop() (Looper.java:211)
[INFO] :   art: art/runtime/runtime.cc:295]   at void org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run() (KrollRuntime.java:112)
[INFO] :   art: art/runtime/runtime.cc:295] Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.analytics.GoogleAnalytics" on path: DexPathList[[zip file "/data/app/com.superchamba.scapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.superchamba.scapp-1/lib/arm, /vendor/lib, /system/lib]]
[INFO] :   art: art/runtime/runtime.cc:295]   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
[INFO] :   art: art/runtime/runtime.cc:295]   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:511)
[INFO] :   art: art/runtime/runtime.cc:295]   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:469)
[INFO] :   art: art/runtime/runtime.cc:295]   at void analytics.google.AnalyticsGoogleModule.<init>() (AnalyticsGoogleModule.java:45)
[INFO] :   art: art/runtime/runtime.cc:295]   at java.lang.Object java.lang.reflect.Constructor.newInstance!(java.lang.Object[], boolean) (Constructor.java:-2)
[INFO] :   art: art/runtime/runtime.cc:295]   at java.lang.Object java.lang.Class.newInstance() (Class.java:1606)
[INFO] :   art: art/runtime/runtime.cc:295]   at org.appcelerator.kroll.KrollProxy org.appcelerator.kroll.KrollProxy.createProxy(java.lang.Class, org.appcelerator.kroll.KrollObject, java.lang.Object[], java.lang.String) (KrollProxy.java:142)
[INFO] :   art: art/runtime/runtime.cc:295]   at void org.appcelerator.kroll.runtime.v8.V8Runtime.nativeRunModule(java.lang.String, java.lang.String, org.appcelerator.kroll.KrollProxySupport) (V8Runtime.java:-2)
[INFO] :   art: art/runtime/runtime.cc:295]   at void org.appcelerator.kroll.runtime.v8.V8Runtime.doRunModule(java.lang.String, java.lang.String, org.appcelerator.kroll.KrollProxySupport) (V8Runtime.java:177)
[INFO] :   art: art/runtime/runtime.cc:295]   at boolean org.appcelerator.kroll.KrollRuntime.handleMessage(android.os.Message) (KrollRuntime.java:299)
[INFO] :   art: art/runtime/runtime.cc:295]   at boolean org.appcelerator.kroll.runtime.v8.V8Runtime.handleMessage(android.os.Message) (V8Runtime.java:203)
[INFO] :   art: art/runtime/runtime.cc:295]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:98)
[INFO] :   art: art/runtime/runtime.cc:295]   at void android.os.Looper.loop() (Looper.java:211)
[INFO] :   art: art/runtime/runtime.cc:295]   at void org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run() (KrollRuntime.java:112)
[INFO] :   art: art/runtime/runtime.cc:295] Dumping all threads without appropriate locks held: thread list lock mutator lock
[INFO] :   art: art/runtime/runtime.cc:295]
[INFO] :   libc: Suppressing debuggerd output because prctl(PR_GET_DUMPABLE)==0
`

**Comment by soumyakantikar** [comment]
@efrainpb This is due to the conflict in the Google Play Services library across various modules. This is a known issue even from Appcelerator's end. Check this link:
http://stackoverflow.com/questions/35731035/android-module-with-google-play-conflict-during-build

We are working on a resolution for it and will try out certain steps to confirm if those will resolve the issue or not. Meanwhile, you can following what Fokke has mentioned in the stackoverflow link. Apart form those steps if you fine any other alternative step, then do let us know.

**Comment by astjohn** [comment]
Most likely related to #48.
