### ISSUE TITLE
App using analytics.google fails to build on Android 

### ISSUE THREAD

**Issue by shodanuk** [Sitata/titanium-google-analytics#48]
Environment:

Mac OSX 10.10.5
Ti CLI 5.0.4
Ti SDK 5.0.0.GA
Targetting Android SDK 21
Android build tools 22.0.1

```
[ERROR] Failed to run dexer:
[ERROR]
[ERROR] Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
[ERROR]
[ERROR] UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/LocationSource;
[ERROR]         at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
[ERROR]         at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
[ERROR]         at com.android.dx.command.dexer.Main.processClass(Main.java:732)
[ERROR]         at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
[ERROR]         at com.android.dx.command.dexer.Main.access$300(Main.java:83)
[ERROR]         at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
[ERROR]         at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
[ERROR]         at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
[ERROR]         at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
[ERROR]         at com.android.dx.command.dexer.Main.processOne(Main.java:632)
[ERROR]         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
[ERROR]         at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
[ERROR]         at com.android.dx.command.dexer.Main.run(Main.java:246)
[ERROR]         at com.android.dx.command.dexer.Main.main(Main.java:215)
[ERROR]         at com.android.dx.command.Main.main(Main.java:106)
[ERROR] 1 error; aborting
```

Removing analytics.google module results in a successful build.

**Comment by astjohn** [comment]
Hi @shodanuk. Thanks for the report. Was this run on your own app or on the test app in the repo? Are you able to update and run the test app for 5.0.0.GA?

**Comment by shodanuk** [comment]
Hi,

The test app in the repo builds ok but then crashes as soon as it starts with the following (both before & after updating the ti sdk in tiapp.xml):

```
[ERROR] TiApplication: (KrollRuntimeThread) [47,180] Sending event: exception on thread: KrollRuntimeThread msg:java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/analytics.google.test-1/base.apk"],nativeLibraryDirectories=[/data/app/analytics.google.test-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libanalytics.google.so"; Titanium 3.5.0,2015/01/12 15:33,0014f83
[ERROR] TiApplication: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/analytics.google.test-1/base.apk"],nativeLibraryDirectories=[/data/app/analytics.google.test-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libanalytics.google.so"
[ERROR] TiApplication: 	at java.lang.Runtime.loadLibrary(Runtime.java:366)
[ERROR] TiApplication: 	at java.lang.System.loadLibrary(System.java:989)
[ERROR] TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:132)
[ERROR] TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:99)
[ERROR] TiApplication: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:185)
[ERROR] TiApplication: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)
[ERROR] AndroidRuntime: FATAL EXCEPTION: KrollRuntimeThread
[ERROR] AndroidRuntime: Process: analytics.google.test, PID: 17321
[ERROR] AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/analytics.google.test-1/base.apk"],nativeLibraryDirectories=[/data/app/analytics.google.test-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libanalytics.google.so"
[ERROR] AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:366)
[ERROR] AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:989)
[ERROR] AndroidRuntime: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:132)
[ERROR] AndroidRuntime: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:99)
[ERROR] AndroidRuntime: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:185)
[ERROR] AndroidRuntime: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)
```

**Comment by shodanuk** [comment]
Interestingly, if I add a reference to ti.map in the tiapp.xml of your test project, I get the dexer error I originally reported.

Then if I remove the analytics.google reference but leave the ti.map ref, it builds ok.

Looks like it might be a conflict with ti.map?

**Comment by kerbooo** [comment]
I don'T compile my project because of same issue. Older versions of your modules don't compile too.

**Comment by kerbooo** [comment]
Yes when I remove ti.admob module from my project it complied.

**Comment by kerbooo** [comment]
Looks like it might be a conflict with all ti.*** modules. 
example: ti.admob - ti.dfp - ti.map

**Comment by kerbooo** [comment]
@shodanuk do you know any alternative analytics module working with sdk 5.0

**Comment by shodanuk** [comment]
@kerbooo I don't about any other working ones but you might find others on http://gitt.io.

@astjohn I'm afraid my native skills aren't up to much but there's anything else I can do to help debug this, please let me know.

**Comment by kerbooo** [comment]
Hi @shodanuk I solved my problem. I get help from this link https://developer.appcelerator.com/question/141306/how-can-i-know-my-titanium-module-path 

I am using ti.admob and this module in my project. I think you are using Mac OS. Installed modules path on mac os like this /Users/<your user name>/Library/Application Support/Titanium/modules 

Find your modules which are using on your project. Every modules has got "lib" folder. 

This module use a jar file which name is "google-play-services.jar" 

Looks like it might be a conflict with if your other module use same or like "google-play-services-base.jar" files. May be you can delete or use same "google-play-services.jar" for your project.

**Comment by shodanuk** [comment]
@kerbooo Hey. Thanks for the tip. Unfortunately, I've already tried this but it didn't work for me. Ti.map doesn't use the standard google-play-services.jar anymore but now has two libs: google-play-services-base.jar & google-play-services-map.jar. I tried dropping in google-play-services-base.jar but that didn't seem to work.

**Comment by kerbooo** [comment]
@shodanuk There was same thing for me I found "ti.admob" 's older version which using "google-play-services.jar" I solved with this version. May be you can find analytics module which use "google-play-services-base.jar"

**Comment by shodanuk** [comment]
@kerbooo Maybe. I've tried most of the others but they weren't as good as this one. Hoping it gets fixed soon :)

**Comment by astjohn** [comment]
Hey guys. Apologies because I've been swamped recently, but perhaps I can take a deeper look this weekend. I was also one of the authors for the recent drawing additions to Ti.Map and so it's in Sitata's best interest to make sure the two modules play nice with each other.

**Comment by jpriebe** [comment]
You might want to look at my [pull request](https://github.com/Sitata/titanium-google-analytics/pull/44), which gets into issues of google play services compatibility.  I think this is one of the biggest problems Titanium has on the android platform.  It's getting harder and harder to build an android app and *not* run into this problem.

**Comment by vladcvoinescu** [comment]
@kerbooo I have exactly the same problem as you had but I cannot seem to solve it. Can you please tell me what exactly to rename and what should be the new name of the jar?

**Comment by kerbooo** [comment]
@vladcvoinescu Hi I am using ti.module and this module in my project. If you are using same modules too. You can import ti.admob module's 2.1.4 version and this module's lasted version. So yo don't do to need anything more and any fix.

ti.module's link: https://github.com/appcelerator-modules/ti.admob/releases/tag/android-2.1.4

**Comment by vladcvoinescu** [comment]
Ok, after about 8 hours of trial and error during a few days, I eventually fixed it by removing all the jars that were in the lib folder of the modules that I use (admob, google analytics) and replacing them with the complete one from the android sdk tools (C:\android-sdk-win\extras\google\google_play_services\libproject\google-play-services_lib\libs). If you decide to follow this method, bare in mind that you will have to delete the modules from C:\ProgramData\Titanium\modules\android first, then recompile them using the complete GPS jar (- in case you are deploying the modules for Titanium SDK, if not, you will probably have to delete the modules from your project).

@kerbooo Thank you for the fast reply. I should have posted earlier and maybe would've won some hours with your help :) I used the aforementioned method and it worked for me.

**Comment by kerbooo** [comment]
@vladcvoinescu my native skills is not good. Do you share your modified modules with me?

**Comment by kerbooo** [comment]
@vladcvoinescu  When I was using MAC OSX, lasted titanium sdk was 5.xx I installed Appcelerator Studio for windows from Appcelerataor Platform, Studio is installing mobilesdk-3.5.1RC is it normal?  And studio doesn't update anything after installation finished.

**Comment by shodanuk** [comment]
I only have two modules in my app that include Google Play Services: ti.map & analytics.google. I removed the gps jar from the analytics.google module's lib folder but unfortunately I am now seeing what can only be described as one of the biggest stack traces I've ever encountered.

Please see: http://pastebin.com/5DDPBBER

Again, removing the analytics.google module "fixes" this.

There definitely seems to be a compatibility issue between analytics.google & ti.map and I'm also now wondering if the problem would also occur between ti.map & any other module that uses google play services.

**Comment by jpriebe** [comment]
This sort of google play services conflict is becoming a really big problem for Titanium developers.  

I think you can solve this problem using the technique that I [outline here](https://github.com/jpriebe/ti.dfp/issues/13) (in my last couple of comments).

The bottom line is that I think you're going about things backwards.  I think you should use the google play services jar from analytics.google, not the one from ti.map.  IIRC, the one shipped with ti.map is not complete; it is stripped down to just the code that is required for google maps.  So you don't want to use that one with analytics.  Use the full JAR shipped with analytics with the ti.map module.

I realize that means modifying a module that is shipped by Appcelerator, but I can tell you that it has worked for us so far.  I am using my forked version of titanium-google-analytics, which I have updated to the latest google play services (or at least it was the latest when I did that a month ago).

**Comment by shodanuk** [comment]
Hmm ok. The reason I pulled out the analytics.google google play services lib included with ti.map appears to have been split into 2 parts with slightly different names: "google-play-services-base.jar" + "google-play-services-map.jar". @jpriebe, Presumably this is what you're referring to when you say the version of google play services that ships with ti.map is "stripped down"?

**Comment by jpriebe** [comment]
Yes, that's what I mean.  See [this article](http://android-developers.blogspot.com/2014/12/google-play-services-and-dex-method.html) for details about how developers can now selectively use individual APIs from Google Play Services.  But if you only have the base and the map API JAR files, you won't have the analytics code, so it's no big surprise that titanium-google-analytics isn't working.

Thus I suggest just getting all the modules synced up on a single google play services JAR file that includes enough for all of them.  It's a royal PITA, but I don't know a better way around it.

**Comment by beaurepair** [comment]
I've had this same problem, and my workaround for now was to revert ti.cloudpush back to v 3.3.8 and ti.map back to 2.3.1 (both the second most recent versions). They must be using updated gps jar.

**Comment by jabele** [comment]
I can confirm that removing the google-play .jar files from all the non Google Analytics module lib folders and replacing them with the google-play-services.jar from the Google Analytics lib folder works great. It appears Google Analytics has a full version and most other modules use a smaller .jar file. Having just one that is all-encompassing and keeping them in sync seems to work great so far.

**Comment by ciauri** [comment]
Having the same issue. Attempted jabele's solution which allows the dexer to complete but then results in an insta-crash on app launch.

I copied the google-play-services.jar from the GA module lib folder, deleted the partial gps jars from the ti.map lib folder, and replace them with the single google-play-services.jar.

Unfortunately the app doesn't leave a stack trace on crash, so it's difficult to troubleshoot this further.

**Comment by ciauri** [comment]
An entire day of troubleshooting and I figured out a solution!

What I ended up doing was replacing one of the `google-play-services.jar` with the official jar that you can download from the Extras section of the Google SDK manager (`./android`) tool. Once that was done, I deleted all other gps jars from other modules that may contain it.

The last step of this process is a bit more convoluted:
Each of the add-on modules have a `platform/android/res/` that contains a `version.xml` file inside of which has a line with `google_play_services_version` and an integer. All you have to do is change that value to the correct gps version and you're set!

The only drawback to this approach is that it will likely cause you to hit your 64K Dalvik references limit since you're importing the entirety of the Google Play Services jar. I'm sure there is a way to work around that, but this solution works for my use case.

Good luck!

**Comment by soumyakantikar** [comment]
After going through the link which @jpriebe had shared, which states the separation of the Google Play libraries into smaller parts, there is something for analytics. What I was wondering is that instead of using the entire google-play-service JAR, can we not use the google-play-service-base and google-play-service-analytics instead? I have not tried it, but just a thought which I wanted to share. One such link to the JAR file is, https://github.com/dandar3/android-google-play-services-analytics. I do not know the version number of it though.

**Comment by astjohn** [comment]
@soumyakantikar This is 100% the best approach if possible. I realize I've been out of touch lately, but I've been completely swamped. If someone can attempt this and make a proper pull request, I'm all for it. Anything moving forward should be backwards compatible to the lower Titanium API's. i.e. see if it will work with the minimum Titanium API that's currently specified.

**Comment by soumyakantikar** [comment]
I will work on this in the weekend and update as to whether it is working or not. I have had posted a query in StackOverflow too, where Fokke has responded. If anyone is interested, then you can follow up. There is a TIMOD ticket also open.

http://stackoverflow.com/questions/35731035/android-module-with-google-play-conflict-during-build

**Comment by soumyakantikar** [comment]
After adding google-play-services-analytics.jar to the module, we are still getting the dex error. For testing, if we remove the base.jar from the lib folder of CloudPush, then in that case the dex error is not coming. Hence, there are functions which are present in both base.jar and in the analytics.jar. As Fokke, mentioned I guess, there is no other way, as of now, than to remove the JAR files from all the modules than one so that the duplicate issue is not generated. I will still continue to see if there is any other process.

**Comment by soumyakantikar** [comment]
When using the google-play-services-analytics.jar from the following link then the module is building properly, no dex is found. But, the only catch is that this JAR needs google-play-services-base.jar to be present, and if using this module in conjunction with another TiModule (for example TiCloudPush) then in that case the dex error is generated again and we need to remove the base.jar from this module (no need to modify the Appcelerator modules). Now I will test and confirm that the applications are building properly and that they are functioning properly.

**Comment by annamf** [comment]
I've created a new module project with your java files to check if the problem can be produced by the project, but no. The problem is the same.

If I introduce 2 different google_play_services.jar files, Appcelerator tells me.  But in this case I haven't got this error.

I need to solve this quickly, because my boss.

My error is in both modules (yours & mine):

```
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzrn;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzrp;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzro;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzrl;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzrm;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/zzc;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/ConnectionResult;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/zza;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/Scopes;
```

**Comment by annamf** [comment]
The temporary solution for me is:

1.- Download ti.map master from gitHub
2.- Change google-play-services-base.jar and google-play-services-map.jar  --> for google.play-services.jar (the same that analytics.google project)
3.- Change in version.xml the number 7571000 --> to 6171000
4.- Compile the module

Then, the two libraries can work together.

**Comment by soumyakantikar** [comment]
@annamf Yes, this approach will also work.

**Comment by annamf** [comment]
@soumyakantikar Sorry, It doesn't work. Ti.map doesn't work with the google-play-services.jar some classes are missing. 
Where can I find the google-play-services-analytics.jar??? or another google-play-services.jar that includes all the libraries about maps??

**Comment by soumyakantikar** [comment]
I will create the PR. For my test scenario, Google Analytics is working fine with Google Cloud Push and they are working in harmony. I have tried it with 5.2.0.GA. Would request others to test and confirm.

**Comment by AdamLVC** [comment]
Hi all. I seem to be experiencing a similar issue, but I am only using the singular Analytics module, not the map one. This is the error message i'm getting:

```
[ERROR] :  AndroidRuntime: FATAL EXCEPTION: KrollRuntimeThread
[ERROR] :  AndroidRuntime: Process: com.****, PID: 8783
[ERROR] :  AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.****-1/base.apk"],nativeLibraryDirectories=[/data/app/com.****-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libanalytics.google.so"
[ERROR] :  AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:366)
[ERROR] :  AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:989)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:132)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:99)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:205)
[ERROR] :  AndroidRuntime: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:114)
```

I'm currently using Titanium SDK 5.2.1, and i'm using the Android SDK 6.0 (Level 23).

Any suggestions / guidance would be much appreciated. I've tried the above to no avail.

**Comment by dineshkoli** [comment]
Hi @annamf,
I have done the changes as per you said, but when showing map app crashing..
[ERROR] :  TiApplication: (main) [7920,27089] Sending event: exception on thread: main msg:java.lang.NoClassDefFoundError: ti.map.TiUIMapView; Titanium 5.2.1,2016/03/18 22:51,23e1c7d
[ERROR] :  TiApplication: java.lang.NoClassDefFoundError: ti.map.TiUIMapView
[ERROR] :  TiApplication: 	at ti.map.ViewProxy.createView(ViewProxy.java:79)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:492)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:478)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:516)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:500)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:478)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:516)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:500)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:478)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:516)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:500)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:478)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleAdd(TiViewProxy.java:679)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.add(TiViewProxy.java:573)
[ERROR] :  TiApplication: 	at ti.modules.titanium.ui.WindowProxy.windowCreated(WindowProxy.java:258)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiActivi
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiBaseActivity.windowCreated(TiBaseActivity.java:524)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:638)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiActivity.onCreate(TiActivity.java:18)
[ERROR] :  TiApplication: 	at android.app.Activity.performCreate(Activity.java:6259)
[ERROR] :  TiApplication: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
[ERROR] :  TiApplication: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:148)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5443)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

is there any solution on it.?

**Comment by astjohn** [comment]
@soumyakantikar, I think I'm making progress and made a new branch, but haven't had time to test yet. Can you (or anyone else) please see if it works and report back. Thanks!

New version number will be 3.2.0. Use the zip in this folder:
https://github.com/Sitata/titanium-google-analytics/tree/3.2.0/android/dist

Please treat it as an unstable release candidate.

**Comment by dineshkoli** [comment]
**@astjohn**  
Thanks for giving reply on this issue. I really appreciate your work.

I have tested this module of version 3.2.0 but it not working.
Giving me following errors-
[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/zzau$zza$zza;
[ERROR] :  	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
[ERROR] :  	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
[ERROR] :  	at com.android.dx.command.dexer.Main.processClass(Main.java:732)
[ERROR] :  	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
[ERROR] :  	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
[ERROR] :  	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
[ERROR] :  	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
[ERROR] :  	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
[ERROR] :  	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
[ERROR] :  	at com.android.dx.command.dexer.Main.run(Main.java:246)
[ERROR] :  	at com.android.dx.command.dexer.Main.main(Main.java:215)
[ERROR] :  	at com.android.dx.command.Main.main(Main.java:106)
[ERROR] :  1 error; aborting

**Comment by dineshkoli** [comment]
I gone through these 2 modules **ti.map** and **google.analytics** of versions 2.3.6(latest) and 3.2.0 respectively. 
**ti.map** module's lib folder contains **google-play-services-analytics.jar** and **google-play-services-base.jar**
AND
**google.analytics** module's lib folder contains **google-play-services-map.jar** and **google-play-services-base.jar**

Means they are containing same **google-play-services-base.jar** file. Because of that this error is coming.

I have removed this jar alternatively from these 2 module and run the app but failed.
App cant run or installed in mobile or in android emulators.

Can you please look into this issue.
Thanks in advance..

**Comment by astjohn** [comment]
@dineshkoli You're correct. Appcelerator has chosen to create this base.jar and other jars as a way to trim down google play services for apps that don't need all of google play services. This means that all modules which use google play services must include both base.jar and whatever other trimmed down jar is necessary. Here it is analytics.

As a result, all modules now need to include base.jar and the other jar file. This is for the case when a user is only using one module using google play services. However, our app and your app both use maps AND analytics. 

This might mean that we always need to remove base.jar from one of the modules. I'm not sure. It might also mean that the stripped down analytics.jar that I made included some things that are already in base.jar. I'm still trying to figure out how they stripped down the jars to make base.jar and map.jar. Clearly, the stripped down analytics.jar file I made has some overlap with something that's in base.jar. I think if we can figure this bit out then we'll have a working solution.

**Comment by astjohn** [comment]
@dineshkoli I pushed some updates. Can you please try again?

You will have to replace the base.jar in other modules with the one from this module.

**Comment by dineshkoli** [comment]
**@astjohn** I have used your updated code and replace base.jar. And it working fine..
Great work **astjohn**.
Thanks a lot for your help.. :)

**Comment by soumyakantikar** [comment]
@astjohn I have been held up with multiple tasks recently and hence could not look into it. But from the changes and the post, I would say that we both are going in the same direction. We need to include the analytics.jar and use the base.jar from other modules, if we are including multiple Google Play dependent modules. I will look into it from my end too and confirm.

**Comment by asiby** [comment]
Hi guys.

Thanks for all these great contributions. I think that found a solution that can work for every body.

First of all, it seems like finding the proper jar files from a safe trustable source is quite difficult. For that, simply install Android Studio and let Grade find the jars for you (regardless of the version). You can find all the Grade package names for the Google Play Services sub-packages at https://developers.google.com/android/guides/setup#add_google_play_services_to_your_project.

Then, find the jar files in your project directory and rename them appropriately because they will all be called classes.jar in a package specific directory.

The following is an example that I have got in my project directory ...

```
./app/build/intermediates/exploded-aar/com.google.android.gms/play-services-analytics/8.4.0/jars/classes.jar   ---(rename to)---> google-play-services-analytics.jar

./app/build/intermediates/exploded-aar/com.google.android.gms/play-services-base/8.4.0/jars/classes.jar   ---(rename to)---> google-play-services-base.jar
 
./app/build/intermediates/exploded-aar/com.google.android.gms/play-services-basement/8.4.0/jars/classes.jar   ---(rename to)---> google-play-services-basement.jar
 
./app/build/intermediates/exploded-aar/com.google.android.gms/play-services-gcm/8.4.0/jars/classes.jar   ---(rename to)---> google-play-services-gcm.jar
 
./app/build/intermediates/exploded-aar/com.google.android.gms/play-services-maps/8.4.0/jars/classes.jar   ---(rename to)---> google-play-services-maps.jar
```
Then use the combination of the google-play-services-basement.jar and google-play-services-base.jar plus any other jar that you need (maps, analytics, etc.)

So the steps are ...

1. Create an project in Android Studio
2. Modify the build.gradle file and added the google-play-services-* dependencies that you need and sync the project so that the needed files are all downloaded.
3. Find the jar files and rename them appropriately.
4. Copy the jar files everywhere in titanium modules wherever they are needed (even in Titanium modules that you may be building). 
5. Compile the project.
6. Enjoy

Not that you do not need to be careful about not duplicating the jars are long as they have they are identical (ex. from the same version of Google Play Services).

If you are building a module, it can happen that you receive an error message about the expected version vs the used version. In such case, set the version manually.

The example below show what I had to do in my module (the expected version was 8487000) ...

```
<!-- <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/> -->
<meta-data android:name="com.google.android.gms.version" android:value="8487000"/>
```

**Comment by soumyakantikar** [comment]
It is working properly and the data are getting posted into Google Analytics. Any body else found any issue or has any update on the same?

**Comment by ygbr** [comment]
Hi @soumyakantikar have you used the solution above from @asiby ? Are you running Titanium 5.2.2.GA ?

**Comment by ericpolkadoc** [comment]
@soumyakantikar @asiby @astjohn -- im having some trouble getting the solution to work, using analytics and maps.  What Ive done:

- built a sample android project, and pulled down all the individual google play service jars.
- renamed and moved each classes.jar to my project's module directory, ie:
-- /Users/me/Documents/Appcelerator_Studio_Workspace/ProjectName/modules/android/analytics.google/3.2.0/lib/google-play-analytics.jar
-- /Users/me/Documents/Appcelerator_Studio_Workspace/ProjectName/modules/android/analytics.google/3.2.0/lib/google-play-services-base.jar

Did same thing for Titanium installed Modules, ie ti.map 
-- /Users/me/Library/Application Support/Titanium/modules/android/ti.map/2.3.10/google-play-services-base.jar
-- /Users/me/Library/Application Support/Titanium/modules/android/ti.map/2.3.10/google-play-services-maps.jar

and Ti.CloudPush
-- /Users/me/Library/Application Support/Titanium/modules/android/ti.cloudpush/3.4.1/google-play-services-gcm.jar
/Users/me/Library/Application Support/Titanium/modules/android/ti.cloudpush/3.4.1/google-play-services-base.jar

Ive tried it with and without the google-play-services-basement.jar

Ive tried it by naming the .jars as suggested above using google-play-services-*.jar and also the way the 9.4.0 version I pulled down in my sample android application, simply as play-services-.*.jar.

Ive verified all jars are the same version of play services, which is 9.4.0.

When I launch my app with google.analytics in, I get a crash on start up.

Upon commenting it out, the app runs normally.

Any thoughts on what might be happening or if Ive missed something?

Thanks!

**Comment by deckameron** [comment]
Hello guys,

I know it is an old issue and most of you probably have already solved it, but I thought I should share with with the ONLY solution I could find. It's Proguard!
It is really simple and easy to use (in this case) and the tutorial is [here](https://medium.com/all-titanium/deal-with-titanium-modules-and-its-missing-support-for-android-multidex-546de5486d13#.y4t50z77p).
Hope you enjoy and that it helps you as well.

**Comment by asiby** [comment]
Hello Soumya

This is an interesting link. Thanks.

**Comment by caiocost** [comment]
@ericpolkadoc im having the same issue, when i use ti.map and analytics.google together the app crash, no matter what version of both and titanium sdk that i use, it still crashes running an fresh new app for tests, no errors on console...

did you found any solution on this?

**Comment by lulap** [comment]
what facility is provided for users not keen on being part of analytics to opt-out?  without cracking your app

**Comment by asiby** [comment]
None.

It's up to each app developer to have that in the settings ... then disable
the analytics module accordingly. However, one has to ask what someone
could be hiding if they are trying to opt out of Google Analytics in a
simple mobile app (I am assuming it's a simple app). Most of the time, it
is used in order to improve the content delivery flow of the app by knowing
how people are using the app.

In our case, we have simply explained what we are really doing with Google
Analytics and that it cannot and will not be disabled. If they do not want
that, then they should not install our app. None of the data we collect can
be used to identify a user. We just want to collect information that will
help us know the most used features in the app, the most popular pages, the
number of time the app is launched, etc. Most importantly, we never collect
the GPS location because that can be used for pin pointing a user by
linking them with a physical address.

A. Siby

**Comment by kerberosargos** [comment]
Hi Guys I solved Google Play Services conflict for using more Titanium modules. I have recorded a screencast for solution. You can find it from https://youtu.be/Coei6zvPIys

May be that is help for somebody...
