### ISSUE TITLE
Class JavaLaunchHelper Issue for Android

### ISSUE THREAD

**Issue by abircse06** [Sitata/titanium-google-analytics#51]
i build the module from the source using the titanium SDK 4.0.0.GA and when I add the module to my app , it shows me this error 

[ERROR] Application Installer abnormal process termination. Process exit value was 1
[ERROR] : Failed to run dexer:
[ERROR] :
[ERROR] : objc[7020]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
[ERROR] :
[ERROR] : UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] : java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/dynamic/LifecycleDelegate;
[ERROR] : at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
[ERROR] : at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
[ERROR] : at com.android.dx.command.dexer.Main.processClass(Main.java:732)
[ERROR] : at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
[ERROR] : at com.android.dx.command.dexer.Main.access$300(Main.java:82)
[ERROR] : at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
[ERROR] : at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
[ERROR] : at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
[ERROR] : at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
[ERROR] : at com.android.dx.command.dexer.Main.processOne(Main.java:632)
[ERROR] : at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
[ERROR] : at com.android.dx.command.dexer.Main.runMonoDex(Main.java:279)
[ERROR] : at com.android.dx.command.dexer.Main.run(Main.java:245)
[ERROR] : at com.android.dx.command.dexer.Main.main(Main.java:214)
[ERROR] : at com.android.dx.command.Main.main(Main.java:106)
[ERROR] : 1 error; aborting
TRACE | titanium exited with exit code 1
ERROR | Error: ti run exited with error code 1
at ChildProcess.<anonymous> (/Users/touhidurrahman/.appcelerator/install/4.0.1/package/node_modules/appc-cli-titanium/plugins/run.js:84:66)
at ChildProcess.emit (events.js:98:17)
at Process.ChildProcess._handle.onexit (child_process.js:810:12)

now when i remove the module from my app for the Android , then the app is working fine and no such issue . according to my search , this issue is caused by a JAVA bug and oracle has already fixed it . but for some reason , when i add the module , it's causing this problem . i am not sure if this related to the titanium SDK 4.0.0.GA as i used this module to my other apps before without building it from the source and i did not face such problem . 

working fine for the iOS so far . 

Here is my current configs :
Mac OS 10.10.3
Appcelerator Studio build: 4.0.0.201505202026
Titanium SDK 4.0.0.GA
JDK 1.7.0_80
Appcelerator Command-Line Interface, version 4.0.1

Testing device :
Nexus 5 Running Android OS 6.0

Testing Emulators : (i am using genymotion for the android emulator testing)
Google Nexus 5 - 5.1.0 - API 22
Google Nexus 6 - 5.1.0 - API 22

**Comment by vasilestefirta** [comment]
I have a similar issue. In my case the error appears when I have both Google Analytics and the Push Client (https://github.com/arleyandrada/PushClient) modules installed in the same time.

**Comment by vasilestefirta** [comment]
The author of the PushClient module said that you guys most probably need to update the Google Play Services of your module in order to fix this conflict issue.

https://github.com/arleyandrada/PushClient/issues/113#issuecomment-170791779

Could you guys please do that and release a new version of the Google Analytics module.

Thank you in advance!

**Comment by vasilestefirta** [comment]
Hey guys,

Any updates on this issue? It would be amazing if you can release a fix for this issue :)

Thanks a lot!

**Comment by astjohn** [comment]
Most likely duplicate of #48
