### ISSUE TITLE
Android - Module doesn't work in Ti.SDK 5.1.2.GA 

### ISSUE THREAD

**Issue by annamf** [Sitata/titanium-google-analytics#55]
Hello,

I'm trying to use this module on Android but it shows me this error:

I read that it can be caused by google-play-services.jar, but if I remove this library I can't compile the module. The version 1.0 of this module doesn't work in Android 6.0.

Can anyone help me?
```
Failed to run dexer:
[ERROR] :  
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/LocationSource;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/GoogleMap$4;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/StreetViewPanorama$OnStreetViewPanoramaChangeListener;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/StreetViewPanoramaFragment;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/GoogleMap$InfoWindowAdapter;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/MapsInitializer;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/MapFragment;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/GoogleMap$OnMyLocationButtonClickListener;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/UiSettings;
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.RuntimeException: Translation has been interrupted
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
[ERROR] :  	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
[ERROR] :  	at com.android.dx.command.dexer.Main.run(Main.java:277)
[ERROR] :  	at com.android.dx.command.dexer.Main.main(Main.java:245)
[ERROR] :  	at com.android.dx.command.Main.main(Main.java:106)
[ERROR] :  Caused by: java.lang.InterruptedException: Too many errors
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
[ERROR] :  	... 4 more
```

**Comment by soumyakantikar** [comment]
@annamf Please keep a watch on this ticket:
https://github.com/Sitata/titanium-google-analytics/issues/48

**Comment by annamf** [comment]
Ok, thank you. I hope this problem will be resolved soon.
